project:
  type: website
  output-dir: docs

website:
  title: "Lily Zhou"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - href: CV.qmd
      #   text: CV
      - href: Research.qmd
        text: Research
      # - href: blog.qmd
      #   text: Posts
      - text: About Me
        href: About.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

