---
title: "About Me"
---

I am a second year epidemiology student studying at the Dalla Lana School of Public Health at the University of Toronto.

Prior to studying epidemiology, I completed my degree in nursing and worked in just about every hospital unit during the COVID-19 pandemic.
As a bedside nurse, I became increasingly interested in upstream approaches in health care after experiencing the devastating failures of our current downstream system. While working as a vaccine nurse, I was inspired by Ottawa Public Health and their efforts to uncover the sources of outbreaks and control spread in the community. 
Looking to combine my research and clinical abilities to work in an area targeting the population level, I decided to pursue epidemiology. My goal is to create impactful change within our health care system and systems globally.

Besides academics and work, I love visual arts, rock climbing and hiking.🗻

# Education 

**University of Toronto** | Toronto, ON\

MPH in Epidemiology | September 2022 - April 2023\

**University of Ottawa** | Ottawa, ON\

BSc in Nursing | September 2018 - April 2021\



# Curriculum Vitae 
my CV can be downloaded [here](CV/CV Zhi Lin Zhou 2024.pdf).

Please reach me via email to access my most recent CV.